#!/bin/bash
# Compile GLSL shaders to SPIR-V and MSL, then generate C header with embedded bytecode.
# Usage: ./compile.sh [output_dir]
#
# Requirements:
#   glslangValidator (from Vulkan SDK or Homebrew: brew install glslang)
#   spirv-cross      (from Homebrew: brew install spirv-cross)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUT_DIR="${1:-$SCRIPT_DIR}"
HEADER="$OUT_DIR/ShaderBytecode.h"

GLSLANG="${GLSLANG:-glslangValidator}"
SPIRV_CROSS="${SPIRV_CROSS:-spirv-cross}"

# Verify tools
command -v "$GLSLANG" >/dev/null 2>&1 || { echo "ERROR: glslangValidator not found"; exit 1; }
command -v "$SPIRV_CROSS" >/dev/null 2>&1 || { echo "ERROR: spirv-cross not found"; exit 1; }

SHADERS=(blit.vert blit.frag)
TEMP_DIR=$(mktemp -d)
trap "rm -rf $TEMP_DIR" EXIT

# Compile each shader to SPIR-V and MSL
for s in "${SHADERS[@]}"; do
    echo "Compiling $s.glsl ..."
    "$GLSLANG" -V "$SCRIPT_DIR/$s.glsl" -o "$TEMP_DIR/$s.spv"
    "$SPIRV_CROSS" --msl "$TEMP_DIR/$s.spv" --output "$TEMP_DIR/$s.msl"
done

# Generate C header
echo "Generating $HEADER ..."
cat > "$HEADER" << 'HEADER_TOP'
// Auto-generated by compile.sh — do not edit
#pragma once
#include <cstdint>
#include <cstddef>

namespace vamiga {
namespace shaders {

HEADER_TOP

for s in "${SHADERS[@]}"; do
    # SPIR-V binary → C array
    NAME=$(echo "$s" | tr '.' '_')
    echo "static const uint8_t ${NAME}_spirv[] = {" >> "$HEADER"
    xxd -i < "$TEMP_DIR/$s.spv" >> "$HEADER"
    echo "};" >> "$HEADER"
    echo "static const size_t ${NAME}_spirv_size = sizeof(${NAME}_spirv);" >> "$HEADER"
    echo "" >> "$HEADER"

    # MSL source → C string
    echo "static const char ${NAME}_msl[] = R\"MSL(" >> "$HEADER"
    cat "$TEMP_DIR/$s.msl" >> "$HEADER"
    echo ")MSL\";" >> "$HEADER"
    echo "static const size_t ${NAME}_msl_size = sizeof(${NAME}_msl) - 1;" >> "$HEADER"
    echo "" >> "$HEADER"
done

cat >> "$HEADER" << 'HEADER_BOTTOM'
} // namespace shaders
} // namespace vamiga
HEADER_BOTTOM

echo "Done."
